### ISSUE TITLE
建议增加who's using

### ISSUE THREAD

**Issue by dengzhp** [alibaba/wax#18]
这类应用容易被app store拒,  如果可以列出哪些app在用，可以增强使用者信心。

**Comment by fengjian** [comment]
多余的担心，游戏行业基本全是动态脚本

**Comment by IvanChan** [comment]
这个要看使用方式，如果是用来运行整个app的话，是没问题的

如果是做动态下发可运行代码的话，苹果好像明文规定不允许的，自求多福吧
