### ISSUE TITLE
在lua中怎么解析OC中的自定义类型呢？

### ISSUE THREAD

**Issue by limost** [alibaba/wax#19]
自定义类型为BookInfo包括NSDictionary类型的menu（目录）和NSString类型的name(名字)。
代码如下：
       local gBookInfo = BookInfo:sharedInstance() --gBookInfo是userdata（用户自定义）类型
在Lua中通过BookInfo中的ShareInstance方法，取得实体。现在我需要在Lua中解析gBookInfo的menu字段，却找不到合适的方法。求解答，万分感谢！！！

**Comment by intheway** [comment]
what would you write in OC?
gBookInfo.menu , gBookInfo.name
so in lua
local menu = gBookInfo: menu()
local name = gBookInfo:name()

**Comment by Lost-lin** [comment]
Thanks
