### ISSUE TITLE
How can I get the error message which returned from lua?

### ISSUE THREAD

**Issue by luohui8891** [alibaba/wax#22]
Yo,
How can I get any error message from lua level when I `wax_runLuaString` a lua script (like missing `end`)?

**Comment by intheway** [comment]
wax_start(nil, nil);
    int i = wax_runLuaString("print('hello wax)");
    if(i){
        NSLog(@"error=%s", lua_tostring(wax_currentLuaState(), -1));
    }

**Comment by luohui8891** [comment]
Got it. Thanks.
BTW, why there are many debug log like `NSLog(@"data->waxRetain = YES instance=%@", data->instance);` in the source code, just asking.
