### ISSUE TITLE
build project from source not framework make 3 link error

### ISSUE THREAD

**Issue by godshow** [alibaba/wax#23]
1. "_wax_LongLong_call", referenced from:
_wax_LongLong_call_0 in wax_imp_call_pool.o

2. "_wax_double_call", referenced from:
_wax_double_call_0 in wax_imp_call_pool.o

3. Linker command failed with exit code 1 (use -v to see invocation)

it seems that have a bad data type，how to fix it

**Comment by intheway** [comment]
please use the most updatest code
