### ISSUE TITLE
wax attempt to call global 'toblock' (a nil value)

### ISSUE THREAD

**Issue by jxwjr2003** [alibaba/wax#32]
when I use block in lua, it returns this error. 
This code is exactly the same as the examples, I do not know why.
How do I solve this problem?
thanks a lot.

**Comment by jxwjr2003** [comment]
And I also find that the description in file "wax_block_transfer.h" is not the same as the wiki or examples
"wax_block_transfer.h" is like this
/**
 *  convert to OC block with return value and param's type.
 *  OC code: 
     [self testReturnIdWithFirstIdBlock:^id(id aFirstId, char *aCharPointer, char aChar, short aShort, int aInt, long long aLongLong, float aFloat, double aDouble, bool aBool, NSString *aString, id aId) {
        NSLog(@"aFirstId=%@", aFirstId);
        return @"123";
     }];
 * lua code:
	self:testReturnIdWithFirstIdBlock(
        toobjc(
            function(aFirstId, aBOOL, aInt, aInteger, aFloat, aCGFloat, aId)
            print("aFirstId=" .. tostring(aFirstId))
            return aFirstId
        end
        ):luaBlockWithParamsTypeArray({"id","id", "BOOL", "int", "NSInteger", "float", "CGFloat", "id"})
	)
 */


and wiki says like this

you can use toblock(luaFunction, typeArray) to convert Lua function to OC block. The first item in typeArray must be the return value type(except block that return void and no arguments). (toblock is package of luaBlockWithParamsTypeArray, see lib/stdlib/ext/block.lua)
void block, return void block
    UIView:animateWithDuration_animations_completion(1, 
        toblock(
            function()
                label:setCenter(CGPoint(300, 300))
            end
        ),
        toblock(
                function(finished)
                    print('lua animations completion ' .. tostring(finished))
                end
        ,{"void", "BOOL"})-- return void
    )


I doubt that I do not deeply understand the wiki.
Anybody could help?

**Comment by jxwjr2003** [comment]
it is my fault.

**Comment by lovecactus** [comment]
I've got the exactly same issue. Any suggestion what's the possible reason?
