### ISSUE TITLE
 write with argument list

### ISSUE THREAD

**Issue by passol1988** [alibaba/wax#38]
local alert = UIAlertView:initWithTitle_message_delegate_cancelButtonTitle_otherButtonTitles("title", "message", nil, "cancel", "continue", nil)

**otherButtonTitles** can take multiple arguments, how can I pass the parameters?

**Comment by intheway** [comment]
variable method can't be called dynamically. you can use like this:
```
local alert = UIAlertView:init();
alert:setTitle(title);
alert:setMessage("aaaa");
alert:setTitle("bbbb");
alert:setDelegate(self);
alert:addButtonWithTitle("cancel");
alert:addButtonWithTitle("ok");
alert:setTag(20147701);
alert:show();
```
