### ISSUE TITLE
con't support cocoapod 1.0.0

### ISSUE THREAD

**Issue by zrhdev** [alibaba/wax#39]
Analyzing dependencies
Pre-downloading: `wax` from `https://github.com/alibaba/wax.git`, tag `1.1.0`
[!] The `wax` pod failed to validate due to 1 error:
    - ERROR | attributes: Missing required attribute `source`.

**Comment by wallace1110** [comment]
同上
Analyzing dependencies
Pre-downloading: wax from https://github.com/alibaba/wax.git, tag 1.1.0
[!] The wax pod failed to validate due to 1 error:
- ERROR | attributes: Missing required attribute source.

**Comment by kiddtaurus** [comment]
+1

**Comment by kiddtaurus** [comment]
@zrhdev @wallace1110  @huacnlee  @fsword  @mazhao

**Comment by zrhdev** [comment]
https://github.com/zrhdev/wax.git, you can use it.

**Comment by kiddtaurus** [comment]
Analyzing dependencies
Pre-downloading: `wax` from `https://github.com/alibaba/wax.git`, tag `1.1.0`
**[!] The `wax` pod failed to validate due to 1 error:
    - ERROR | attributes: Missing required attribute `source`.**

pod version 1.0.0

@zavakid  
Pod don't support the url, so can it be used like  " pod 'wax', '~> 1.1.0’ " ?

**Comment by intheway** [comment]
add source ,but annother error happened...

**Comment by zrhdev** [comment]
I had fixed it.

pod 'wax', :git => 'https://github.com/zrhdev/wax.git', :tag => '1.2.1'

**Comment by kiddtaurus** [comment]
It works.

**Comment by sunwell** [comment]
@zrhdev Thx.

But I have a question. When I edit my Podfile like this:
pod 'wax', :path=>'wax.podspec's local path'
I can install wax, but in project, wax is a development directory.

Do u know what does pod do when I edit my Podfile like before?  And when I submit my app to AppStore, is this suitable?

**Comment by zrhdev** [comment]
you can create a private spec repo.
