### ISSUE TITLE
failed when running MapKitExample in sumulator

### ISSUE THREAD

**Issue by passol1988** [alibaba/wax#4]
> Undefined symbols for architecture x86_64:
>   "_wax_LongLong_call", referenced from:
>       _wax_LongLong_call_0 in wax_imp_call_pool.o
>       _wax_LongLong_call_1q in wax_imp_call_pool.o
>       _wax_LongLong_call_1d in wax_imp_call_pool.o
>       _wax_LongLong_call_2qq in wax_imp_call_pool.o
>       _wax_LongLong_call_2qd in wax_imp_call_pool.o
>       _wax_LongLong_call_2dq in wax_imp_call_pool.o
>       _wax_LongLong_call_2dd in wax_imp_call_pool.o
>   "_wax_double_call", referenced from:
>       _wax_double_call_0 in wax_imp_call_pool.o
>       _wax_double_call_1q in wax_imp_call_pool.o
>       _wax_double_call_1d in wax_imp_call_pool.o
>       _wax_double_call_2qq in wax_imp_call_pool.o
>       _wax_double_call_2qd in wax_imp_call_pool.o
 >      _wax_double_call_2dq in wax_imp_call_pool.o
 >      _wax_double_call_2dd in wax_imp_call_pool.o
>       ...

When I run some example in this project ,always get this ...

**Comment by intheway** [comment]
sorry for delete some files, it's ok now. please try again.
