### ISSUE TITLE
说明就不能用中文来写吗？

### ISSUE THREAD

**Issue by kouliang** [alibaba/wax#5]
说明就不能用中文来写吗？最不济也应该一份英文一份中文。全整英文什么心态

**Comment by hytzxd** [comment]
Why don't you complaining about apple‘s api？

**Comment by jackrex** [comment]
英文有啥不好.....

**Comment by intheway** [comment]
这个可以有, 后面我写新的文档弄一份英文的,再弄一份中文的. 
不过历史的文档比较多, 要慢慢来改成中文, 英语好的可以帮忙下.

**Comment by DaidoujiChen** [comment]
佛心來的 :)

**Comment by ivanyang1984** [comment]
写英文 是为了  让老外也看。。

**Comment by intheway** [comment]
把wiki里的install wax的文档重新整理了下. 增加了中文版. 另外不少朋友有交流需求, 建了个qq群196306834和gitter, https://gitter.im/alibaba/wax. 有兴趣的一起聊吧.
虽然我的英文文也比较烂, 但是github上还是尽量使用英文吧.
Thanks!
