### ISSUE TITLE
Rejected Binary 

### ISSUE THREAD

**Issue by hasbean** [alibaba/wax#61]
I've been sent a notice on iTunesConnect saying to update my game or face removal from the App Store.

I've sent an updated version and it's already been rejected twice.  This is what I got when I asked for clarification:

> Hello,
> 
> Thank you for providing this information.
> 
> Regarding 2.5.2, your app, extension, or linked framework appears to contain code designed explicitly with the capability to change your app’s behavior or functionality after App Review approval, which is not in compliance with App Store Review Guideline 2.5.2 and section 3.3.2 of the Apple Developer Program License Agreement..
> 
> Specifically, this app is verified to contain a feature switching hotpatch SDK which is capable of executing remote LUA script as native code. It would be appropriate to remove all such functionality from the app before resubmitting for review.
> 
> We look forward to reviewing your resubmitted app.
> 
> Best regards,
> 
> App Store Review

There is no code being downloaded whatsoever, so I'm not sure where they got that idea from.

Has anyone else received this issue?

**Comment by conanwsz** [comment]
@hasbean The only thing you can do is remove wax and submit your binary again.

**Comment by hasbean** [comment]
@conanwsz not exactly the solution I wanted to hear :(  I have to rewrite the entire backend now.

**Comment by makeitnew** [comment]
Did you resolve this issue?

**Comment by hasbean** [comment]
No not really, I had to rewrite the backend in C++

Complete nightmare, but better than having my app thrown out of the App Store.
