### ISSUE TITLE
用wax实现，把#import “lib.a” 加入到ViewController.m 里面的功能。这个要怎么搞

### ISSUE THREAD

**Issue by Softminilab** [alibaba/wax#62]
意思就是在发布版本之前有个ViewController.m文件，它里面是没有#import “lib.a”这样的头文件引入的，但是我想在发布版本后，用wax实现，把#import “lib.a” 加入到ViewController.m 里面的功能。这个要怎么搞

**Comment by intheway** [comment]
there is no need for header file. just call objective-c class, method
